### PR TITLE
some cleanup + blockclutch

### PR DESCRIPTION
**Pull request by ProfKambing**
added BlockClutch
combined S Tap and W Tap into SprintReset

### CODE REVIEW

**Comment by zPeanut** [comment]
lgtm and you @Morten-Renner ?

**Comment by Morten-Renner** [comment]
code ok, works fine

**Comment by ProfKambing** [comment]
@Morten-Renner do you know how to not spam packets when using bedaura? im making a bypass for hypixel current bedaura patch

**Comment by Morten-Renner** [comment]
We could make a queue like system.
I could implement that tomorrow if you want :)

**Comment by ProfKambing** [comment]
Explain the queue system please. Thanks. Also, sure. I'd love that.

**Pull request merged**
