### PR TITLE
Ok v2.0.1

### PR DESCRIPTION
**Pull request by notperry1234567890**

### CODE REVIEW

**Comment by bush-did-711** [comment]
this isn't spam if you actually look at the changes

**Comment by notperry1234567890** [comment]
> this isn't spam if you actually look at the changes

Idk why they would care/be hurt by that it's the internet but whatev's ppl weird

**Comment by Morten-Renner** [comment]
Regardless of the work itself, such racist terms should not be included in any open source projects (or elsewhere).

I'm not going to start a conversation about the reasons why, so just thank you for the adjustment

**Comment by bush-did-711** [comment]
> Regardless of the work itself, such racist terms should not be included in any open source projects (or elsewhere).
> 
> I'm not going to start a conversation about the reasons why, so just thank you for the adjustment

I am black though I have the pass

**Comment by bush-did-711** [comment]
my apologies though. I am the original author of those comments

**Comment by master7720** [comment]
true^^^^

**Comment by zPeanut** [comment]
what happened here

**Comment by zPeanut** [comment]
btw even if i were to merge this, i cant since ur account got fkn snapped LOL

**Comment by bush-did-711** [comment]
> btw even if i were to merge this, i cant since ur account got fkn snapped LOL

💀

**Pull request closed without merging**
