### PR TITLE
imported BedAura.java from tephra

### PR DESCRIPTION
**Pull request by fawwaz1234**
is this right? if not then close this

### CODE REVIEW

**Comment by fawwaz1234** [comment]
btw i decompiled tephra and copy the code so u dont have to

**Comment by zPeanut** [comment]
you know that i could just copy the code from the tephra github

**Comment by zPeanut** [comment]
ill add it later

**Comment by fawwaz1234** [comment]
LMAOOOOOOOOOOOOOOOOOO

**Pull request closed without merging**
