### PR TITLE
updated caption, more professional

### PR DESCRIPTION
**Pull request by fawwaz1234**

### CODE REVIEW

**Comment by zPeanut** [comment]
you switched up trajectories and projectiles. **trajectories** are the lines being drawn by the actual **projectile**

**Comment by zPeanut** [comment]
also i think the old description fits this more nicely, thanks for the pr though

**Comment by fawwaz1234** [comment]
Actually i stole the desc from kami blue 😳

**Comment by zPeanut** [comment]
no wonder its so shit

**Pull request closed without merging**
